POST /api/v2/auth HTTP/1.1
content-type: application/json

{
    "username":"apioffers",
    "password":"offersC1P8XtpsuKT1ZnL"
}

###

@hostname = localhost
@port = 3500
@host = http://{{hostname}}:{{port}}
@contentType = application/json

###
POST {{host}}/api/v2/auth
Content-Type:{{contentType}}

{
    "username":"apioffers",
    "password":"offersC1P8XtpsuKT1ZnL"
}

###
GET {{host}}/
Content-Type:{{contentType}}
Authorization: token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTcwNjYyMzUsInVzZXIiOiJhcGlvZmZlcnMiLCJpZCI6IjFmMWRjN2Q4LTkzOTUtMTFlOS1iMzA0LTFjMWJiNTUwOGEyZSJ9.ETS2pkwCvifaCgM_HrJ9qbbnP_TSAGQbw3Kp1aDlO5Q

###
